version: '3.9'

services:
  traefik:
    image: traefik:v2.10
    deploy:
      replicas: 1
      restart_policy:
        condition: any
    command:
      - "--providers.docker=true"
      - "--providers.docker.swarmMode=true"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--entrypoints.web.http.redirections.entryPoint.to=websecure"
      - "--entrypoints.web.http.redirections.entryPoint.scheme=https"
      - "--entrypoints.web.http.redirections.entryPoint.permanent=true"
      - "--certificatesresolvers.myresolver.acme.tlschallenge=true"
      - "--certificatesresolvers.myresolver.acme.email=seuemail@dominio.com" # Substitua pelo seu e-mail
      - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
      - "--api.dashboard=false" # Habilita ou dasabilita o painel de controle
    ports:
      - target: 80
        published: 80
        mode: ingress
      - target: 443
        published: 443
        mode: ingress
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - "traefik-data:/letsencrypt"
    networks:
      - traefik-net

volumes:
  traefik-data:

networks:
  traefik-net:
    external: true
